### ISSUE TITLE
Add kbd css style

### ISSUE THREAD

**Issue by Yomisana** [SN-Koarashi/ig-helper#2]
Add this thing make kdb look better
```css
  kbd {
    font-weight: bold;
    padding: 4px 5px;
    background-color: hsl(0deg, 0%, 99%);
    border-radius: 3px;
    border: 1px solid hsl(0deg, 0%, 80%);
  }
  ```
